### ISSUE TITLE
[iOS] Keyboard is block when use slideup notifications, since 1.18 Binding version 

### ISSUE THREAD

**Issue by jmmortega** [braze-inc/braze-xamarin-sdk#11]
Hi,

Keyboard is block and don't appearing when a slide up notification is on.

When any View request the keyboard, this not appearing because a Slide up notification is focus.

Steps to reproduce.

- Use the same sample inside of repository. 
- Include to MainPage something that request Keyboard i.e. an Entry.
- Press Show Slideup to show a sample notification.
- Press inside Entry to focus and request soft keyboard.
- Keyboard not appearing.

Note: Keyboards observers from iOS API like ```UIKeyboard.Notifications.ObserveWillShow``` don't raise.

Attach several gifs to show the error.

![Jan-17-2022 12-32-18](https://user-images.githubusercontent.com/4325509/149762463-7cef255a-51d3-4392-bf2c-3e231dee2eb2.gif)

This error happens since version 1.18.

**Comment by lowip** [comment]
Hi @jmmortega, thank you for reporting this issue. 

We have released the Braze Xamarin SDK version [4.0.1](https://github.com/braze-inc/braze-xamarin-sdk/releases/tag/4.0.1) which now makes use of our Swift SDK, the in-app message UI used in the Swift SDK properly handles the keyboard. 

Please refer to our [changelog](https://github.com/braze-inc/braze-xamarin-sdk/blob/master/CHANGELOG.md#400) entry and sample apps when proceeding to upgrade the SDK.
