### ISSUE TITLE
NuGet package for Android SDK 26.0.0

### ISSUE THREAD

**Issue by akravch** [braze-inc/braze-xamarin-sdk#15]
Hello guys, can you please publish a NuGet package for Xamarin Android that would bind to the [native SDK 26.0.0](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/changelog/#2600)?

I can see that the 26.1.0 targets Android API 34, which can probably be an issue for Xamarin, since it doesn't have support this target yet. But looks like there shouldn't be any issues with wrapping the 26.0.0 into a NuGet.

**Comment by radixdev** [comment]
Hi @akravch ,

We are tracking this and will update this issue once we have updates.

**Comment by radixdev** [comment]
Hi @akravch ,

We've released a new nuget package (2.0.0) with support for Android 26.3.0.
