### ISSUE TITLE
[iOS] AddObserver for Content Cards changes

### ISSUE THREAD

**Issue by bradleyacutts** [braze-inc/braze-xamarin-sdk#16]
Hello,
I am trying to setup an observer to watch for changes to content cards so that we can notify our users that they have new unread cards or so that we can remove the new unread cards badges in our app when the user reads their cards. We I've got it working with the Braze Xamarin Android binding but am having trouble figuring out how to do it with the iOS binding. I have tried the it two different ways (shown below). But I don't know what the string key value that I should be passing in is. In the Braze iOS docs it looks like there is a constant called ABKContentCardsProcessedNotification but I can't find that in the Xamarin binding. Could someone point me in the right direction on how to set this up correctly?

![image](https://github.com/braze-inc/braze-xamarin-sdk/assets/38471841/60c0368d-dba4-4826-a854-8ab85fd6d350)
![image](https://github.com/braze-inc/braze-xamarin-sdk/assets/38471841/7961bd66-fd88-46e9-b96e-c6c4ecc33c51)

**Comment by dveloudos** [comment]
@bradleyacutts was this issue resolved? If so, what was the solution?
