### ISSUE TITLE
[iOS] `BrazeKit` framework is too large

### ISSUE THREAD

**Issue by akravch** [braze-inc/braze-xamarin-sdk#21]
Installing `Braze.iOS.BrazeKit` version 5.0.0 increases the resulting .ipa size by around 11 MB:

![image](https://github.com/braze-inc/braze-xamarin-sdk/assets/8524964/406a0adf-610f-4b63-a107-9143e9b0a9cd)

I see that a lot of it comes from the .swiftmodule framework folder:

![image](https://github.com/braze-inc/braze-xamarin-sdk/assets/8524964/e707ec3e-3aeb-4967-9f1f-f99e6085f994)

As I understand, these files are not really needed in runtime, so even just removing them would reduce the framework size by half.

**Comment by hokstuff** [comment]
Hi @akravch,

Thanks for raising this with a suggestion! We have implemented changes in [Braze Xamarin SDK 6.0.0](https://github.com/braze-inc/braze-xamarin-sdk/releases/tag/6.0.0) which removes these excess files and should help reduce the size of the package.

Thank you!
